tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DWH
      schema: TIH_DEV_DWH
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DWH
      schema: TIH_PROD_DWH
      warehouse: tasty_bytes_dbt_wh
